package org.mryrt.airbnb.notification;

public enum NotificationType {
    BOOKING_APPLIED,
    BOOKING_APPROVED,
    BOOKING_REJECTED,
    BOOKING_REJECTED_ANOTHER_APPROVED,
    BOOKING_CHECKED_IN,
    BOOKING_CHECKED_OUT,
    LISTING_PUBLISHED,
    RESOLUTION_WINDOW_OPENED,
    RESOLUTION_MONEY_REQUESTED,
    RESOLUTION_PAYMENT_RECEIVED,
    RESOLUTION_GUEST_REFUSED,
    RESOLUTION_ESCALATED,
    RESOLUTION_COMPLAINT_RECORDED,
    RESOLUTION_WINDOW_CLOSED,
    RESOLUTION_WINDOW_CLOSED_BY_OWNER,
    RESOLUTION_WINDOW_CLOSED_AUTO,
    RESOLUTION_MANDATORY_PAYMENT_ASSIGNED,
    RESOLUTION_RESOLVED_WITHOUT_PAYMENT
}
