spring.application.name=airbnb-notification

# JMS
airbnb.jms.username=user
airbnb.jms.password=password

# Mail
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
airbnb.mail.from=${MAIL_FROM}
